<?php
/**
 * Promo - Shortcode Options
 */
add_action( 'init', 'havnor_promo_vc_map' );
if ( ! function_exists( 'havnor_promo_vc_map' ) ) {
  function havnor_promo_vc_map() {
    vc_map( array( 
      "name" => __( "Promo", 'havnor-core'),
      "base" => "havnor_promo",
      "description" => __( "Promo Shortcodes", 'havnor-core'),
      "icon" => "fa fa-lightbulb-o color-slate-blue",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Promo Style', 'havnor-core' ),
          'value' => array(
            __( 'Style One', 'havnor-core' ) => 'promo-one',
            __( 'Style Two', 'havnor-core' ) => 'promo-two',
            __( 'Style Three', 'havnor-core' ) => 'promo-three',
            __( 'Style Four', 'havnor-core' ) => 'promo-four',
          ),
          'admin_label' => true,
          'param_name' => 'promo_style',
          'description' => __( 'Select your promo style.', 'havnor-core' ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Toggle Align", 'havnor-core' ),
          "param_name" => "toggle_align",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
        ),
        array(
          "type"      => 'attach_image',
          "heading"   => __('Upload Promo Image', 'havnor-core'),
          "param_name" => "promo_image",
          "value"      => "",
          "description" => __( "Set your promo image.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'vt_icon',
          "heading"   => __('Upload Icon ', 'havnor-core'),
          "param_name" => "promo_icon_image",
          "value"      => "",
          "description" => __( "Set your content icon.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Promo Title', 'havnor-core'),
          "param_name" => "promo_title",
          "value"      => "",
          "description" => __( "Enter your promo title and link.", 'havnor-core'),
          'admin_label' => true,
        ),
        array(
          "type"      => 'textarea_html',
          "heading"   => __('Content', 'havnor-core'),
          "param_name" => "content",
          "value"      => "",
          "description" => __( "Enter your promo content here.", 'havnor-core'),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Promo Button Text', 'havnor-core'),
          "param_name" => "promo_button_text",
          "value"      => "",
          "description" => __( "Enter your promo button text and link.", 'havnor-core'),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Promo Button Link', 'havnor-core'),
          "param_name" => "promo_button_link",
          "value"      => "",
          "description" => __( "Enter your promo button link and link.", 'havnor-core'),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Need Video Link?", 'havnor-core' ),
          "param_name" => "video_link",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'promo_style',
            'value' => array('promo-two', 'promo-three', 'promo-four'),
          ),
        ),
        array(
          "type"      => 'vt_icon',
          "heading"   => __('Set Icon', 'havnor-core'),
          "param_name" => "promo_icon",
          "value"      => "",
          "description" => __( "Set your promo video link icon.", 'havnor-core'),
          'dependency' => array(
            'element' => 'video_link',
            'value' => 'true',
          ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Promo Video Link', 'havnor-core'),
          "param_name" => "promo_video_link",
          "value"      => "",
          "description" => __( "Enter your promo video link.", 'havnor-core'),
          'dependency' => array(
            'element' => 'video_link',
            'value' => 'true',
          ),
        ),
        HavnorLib::vt_open_link_tab(),
        HavnorLib::vt_class_option(),
        // Style
        array(
          "type"      => 'textfield',
          "heading"   => __('Promo Image Left Margin', 'havnor-core'),
          "param_name" => "left_margin",
          "value"      => "",
          "description" => __( "Enter the numeric value for left margin in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        HavnorLib::vt_notice_field(__( "Title Styling", 'havnor-core' ),'tle_opt','cs-warning', 'Style'), // Notice
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Title Color', 'havnor-core'),
          "param_name" => "title_color",
          "value"      => "",
          "description" => __( "Pick your title color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Size', 'havnor-core'),
          "param_name" => "title_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for title size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Font Weight', 'havnor-core'),
          "param_name" => "title_weight",
          "value"      => "",
          "description" => __( "Enter the numeric value for title font weight.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Line Height', 'havnor-core'),
          "param_name" => "title_line_height",
          "value"      => "",
          "description" => __( "Enter the numeric value for title line height.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Bottom Space', 'havnor-core'),
          "param_name" => "title_btm_space",
          "value"      => "",
          "description" => __( "Enter the numeric value for title line height.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Content Color', 'havnor-core'),
          "param_name" => "content_color",
          "value"      => "",
          "description" => __( "Pick your content color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Content Size', 'havnor-core'),
          "param_name" => "content_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for content size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Content Line Height', 'havnor-core'),
          "param_name" => "content_line_height",
          "value"      => "",
          "description" => __( "Enter the numeric value for content size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Content Icon Size', 'havnor-core'),
          "param_name" => "content_icon_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for content icon size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Icon Bottom Space', 'havnor-core'),
          "param_name" => "icon_btm_space",
          "value"      => "",
          "description" => __( "Enter the numeric value for title line height.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Content Icon Color', 'havnor-core'),
          "param_name" => "content_icon_color",
          "value"      => "",
          "description" => __( "Pick your content icon color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),

        // Stlye Three Background color
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Content Background  Color', 'havnor-core'),
          "param_name" => "content_bg_color",
          "value"      => "",
          "description" => __( "Pick your content background color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'promo_style',
            'value' =>  array('promo-three', 'promo-four'),
          ),
        ),
        HavnorLib::vt_notice_field(__( "Button Styling", 'havnor-core' ),'btn_opt','cs-warning', 'Style'), // Notice
        array(
          "type" => "colorpicker",
          "heading" => __( "Text Color", 'havnor-core' ),
          "param_name" => "text_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Image Overlay Color", 'havnor-core' ),
          "param_name" => "img_overlay_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Color", 'havnor-core' ),
          "param_name" => "bgg_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Border Color", 'havnor-core' ),
          "param_name" => "border_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Text Hover Color", 'havnor-core' ),
          "param_name" => "text_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Hover Color", 'havnor-core' ),
          "param_name" => "bg_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Border Hover Color", 'havnor-core' ),
          "param_name" => "border_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Border Radius", 'havnor-core' ),
          "param_name" => "border_radius",
          'value' => '',
          "description" => __( "Enter button border radius. [Eg: 14px]", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Text Size", 'havnor-core' ),
          "param_name" => "text_size",
          'value' => '',
          "description" => __( "Enter button text font size. [Eg: 14px]", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
        ),

      )
    ) );
  }
}
