<?php
/**
 * Difference - Shortcode Options
 */
add_action( 'init', 'havnor_difference_vc_map' );
if ( ! function_exists( 'havnor_difference_vc_map' ) ) {
  function havnor_difference_vc_map() {
    vc_map( array( 
      "name" => __( "Difference", 'havnor-core'),
      "base" => "havnor_difference",
      "description" => __( "Difference Shortcodes", 'havnor-core'),
      "icon" => "fa fa-book color-slate-blue",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          "type"      => 'attach_image',
          "heading"   => __('Upload Difference Image', 'havnor-core'),
          "param_name" => "difference_image",
          "value"      => "",
          "description" => __( "Set your difference image.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Need Icon or Image ?', 'havnor-core' ),
           "param_name" => "image_icon",
          'value' => array(
            __( 'Image', 'havnor-core' ) => 'image-tab',
            __( 'Icon', 'havnor-core' ) => 'icon-tab',
          ),
        ),
        array(
          "type"      => 'attach_image',
          "heading"   => __('Upload Icon Image', 'havnor-core'),
          "param_name" => "difference_icon_image",
          "value"      => "",
          "description" => __( "Set your content image.", 'havnor-core'),
          'dependency' => array(
            'element' => 'image_icon',
            'value' => 'image-tab',
          ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'vt_icon',
          "heading"   => __('Upload Icon', 'havnor-core'),
          "param_name" => "difference_icon",
          "value"      => "",
          "description" => __( "Set your content icon image.", 'havnor-core'),
          'dependency' => array(
            'element' => 'image_icon',
            'value' => 'icon-tab',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Toggle Align?", 'havnor-core' ),
          "param_name" => "tog_align",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Content Align', 'havnor-core' ),
          'value' => array(
            __( 'Content Alignment', 'havnor-core' ) => '',
            __( 'Left', 'havnor-core' ) => 'left',
            __( 'Center', 'havnor-core' ) => 'center',
            __( 'Right', 'havnor-core' ) => 'right',
          ),
          'param_name' => 'content_align',
          'description' => __( 'Select content alignment', 'havnor-core' ),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Difference Title', 'havnor-core'),
          "param_name" => "difference_title",
          "value"      => "",
          "description" => __( "Enter your difference title.", 'havnor-core'),
          'admin_label' => true,
        ),
        array(
          "type"      => 'textarea',
          "heading"   => __('Difference Content', 'havnor-core'),
          "param_name" => "difference_content",
          "value"      => "",
          "description" => __( "Enter your difference content.", 'havnor-core'),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Difference Subtitle', 'havnor-core'),
          "param_name" => "sub_title",
          "value"      => "",
          "description" => __( "Enter your link text.", 'havnor-core'),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Button Text', 'havnor-core'),
          "param_name" => "btn_text",
          "value"      => "",
          "description" => __( "Enter your link text.", 'havnor-core'),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Button Link', 'havnor-core'),
          "param_name" => "btn_link",
          "value"      => "",
          "description" => __( "Enter your button link.", 'havnor-core'),
        ),
        HavnorLib::vt_open_link_tab(),
        HavnorLib::vt_class_option(),
        // Style
        HavnorLib::vt_notice_field(__( "Title Styling", 'havnor-core' ),'tle_opt','cs-warning', 'Style'), // Notice
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Title Color', 'havnor-core'),
          "param_name" => "title_color",
          "value"      => "",
          "description" => __( "Pick your title color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Size', 'havnor-core'),
          "param_name" => "title_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for title size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Icon Color', 'havnor-core'),
          "param_name" => "icon_color",
          "value"      => "",
          "description" => __( "Pick your content icon color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Icon Size', 'havnor-core'),
          "param_name" => "icon_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for content icon size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Sub Title Color', 'havnor-core'),
          "param_name" => "sub_title_color",
          "value"      => "",
          "description" => __( "Pick your sub-title color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Sub Title Size', 'havnor-core'),
          "param_name" => "sub_title_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for sub-title size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Content Color', 'havnor-core'),
          "param_name" => "content_color",
          "value"      => "",
          "description" => __( "Pick your content color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Content Size', 'havnor-core'),
          "param_name" => "content_size",
          "value"      => "",
          "description" => __( "Enter the numeric content for value size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        // Btn Button
        array(
          "type" => "colorpicker",
          "heading" => __( "Text Color", 'havnor-core' ),
          "param_name" => "text_color",
          'value' => '',
          "group" => __( "Button", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Color", 'havnor-core' ),
          "param_name" => "bg_color",
          'value' => '',
          "group" => __( "Button", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Border Color", 'havnor-core' ),
          "param_name" => "border_color",
          'value' => '',
          "group" => __( "Button", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Text Hover Color", 'havnor-core' ),
          "param_name" => "text_hover_color",
          'value' => '',
          "group" => __( "Button", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Hover Color", 'havnor-core' ),
          "param_name" => "bg_hover_color",
          'value' => '',
          "group" => __( "Button", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Border Hover Color", 'havnor-core' ),
          "param_name" => "border_hover_color",
          'value' => '',
          "group" => __( "Button", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Text Size", 'havnor-core' ),
          "param_name" => "text_size",
          'value' => '',
          "description" => __( "Enter button text font size. [Eg: 14px]", 'havnor-core'),
          "group" => __( "Button", 'havnor-core'),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Border Radius", 'havnor-core' ),
          "param_name" => "btn_border_radius",
          'value' => '',
          "description" => __( "Enter button border radius. [Eg: 14px]", 'havnor-core'),
          "group" => __( "Button", 'havnor-core'),
        ),
      )
    ) );
  }
}
