<?php
/**
 * Blog - Shortcode Options
 */
add_action( 'init', 'havnor_blog_vc_map' );
if ( ! function_exists( 'havnor_blog_vc_map' ) ) {
  function havnor_blog_vc_map() {
    vc_map( array(
      "name" => __( "Blog", 'havnor-core'),
      "base" => "hanor_blog",
      "description" => __( "Blog Styles", 'havnor-core'),
      "icon" => "fa fa-newspaper-o color-red",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Blog Style', 'havnor-core' ),
          'value' => array(
            __( 'Style One (List)', 'havnor-core' )    => 'style-one',
            __( 'Style Two (Updates)', 'havnor-core' ) => 'style-two',
            __( 'Style Three (Grid)', 'havnor-core' )  => 'style-three',
            __( 'Style Four (Morden)', 'havnor-core' ) => 'style-four',
            __( 'Style Five (Creative)', 'havnor-core' ) => 'style-five',
            __( 'Style Six (Slider)', 'havnor-core' ) => 'style-six',
          ),
          'admin_label' => true,
          'param_name' => 'blog_style',
          'description' => __( 'Select your blog style.', 'havnor-core' ),
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Columns', 'havnor-core' ),
          'value' => array(
            __( 'Select Blog Columns', 'havnor-core' ) => '',
            __( 'Column Two', 'havnor-core' )    => 'col-2',
            __( 'Column Three', 'havnor-core' )  => 'col-3',
          ),
          'admin_label' => true,
          'param_name' => 'blog_column',
          'description' => __( 'Select your blog column.', 'havnor-core' ),
          'dependency' => array(
            'element' => 'blog_style',
            'value' => array('style-two','style-three','style-four'),
          ),
        ),
        // Blog Style Six 
        array(
          "type"      => 'textfield',
          "heading"   => __('Blog Section Title', 'havnor-core'),
          "param_name" => "blog_six_title",
          "value"      => "",
          "description" => __( "Enter your blog title.", 'havnor-core'),
          'admin_label' => true,
           'dependency' => array(
            'element' => 'blog_style',
            'value' => 'style-six',
          ),
         ),
        array(
          "type"      => 'textarea',
          "heading"   => __('Blog Section Subtitle', 'havnor-core'),
          "param_name" => "blog_six_subtitle",
          "value"      => "",
          "description" => __( "Enter your blog sub title.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' => 'style-six',
          ),
         ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__(' Need Grid Blog Style ?', 'havnor-core'),
          "param_name"  => "need_grid",
          "value"       => "",
          "std"         => false,
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
           'dependency' => array(
            'element' => 'blog_style',
            'value' => 'style-six',
          ),
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Limit', 'havnor-core'),
          "param_name"  => "blog_limit",
          "value"       => "",
          'admin_label' => true,
          "description" => __( "Enter the number of items to show.", 'havnor-core'),
        ),

        array(
    			"type"        => "notice",
    			"heading"     => __( "Meta's to Hide", 'havnor-core' ),
    			"param_name"  => 'mts_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          "type"        => 'checkbox',
          "heading"     => __('Category', 'havnor-core'),
          "param_name"  => "blog_category",
          "value"       => "",
          "std"         => false,
          'edit_field_class' => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Date', 'havnor-core'),
          "param_name"  => "blog_date",
          "value"       => "",
          "std"         => false,
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Author', 'havnor-core'),
          "param_name"  => "blog_author",
          "value"       => "",
          "std"         => false,
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Comments', 'havnor-core'),
          "param_name"  => "blog_comments",
          "value"       => "",
          "std"         => false,
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Date Format', 'havnor-core'),
          "param_name"  => "date_format",
          "value"       => "",
          "description" => __( "Enter date format (for more info <a href='https://codex.wordpress.org/Formatting_Date_and_Time' target='_blank'>click here</a>).", 'havnor-core')
        ),
        array(
    			"type"        => "notice",
    			"heading"     => __( "Listing", 'havnor-core' ),
    			"param_name"  => 'lsng_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order', 'havnor-core' ),
          'value' => array(
            __( 'Select Blog Order', 'havnor-core' ) => '',
            __('Asending', 'havnor-core') => 'ASC',
            __('Desending', 'havnor-core') => 'DESC',
          ),
          'param_name' => 'blog_order',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order By', 'havnor-core' ),
          'value' => array(
            __('None', 'havnor-core') => 'none',
            __('ID', 'havnor-core') => 'ID',
            __('Author', 'havnor-core') => 'author',
            __('Title', 'havnor-core') => 'title',
            __('Date', 'havnor-core') => 'date',
            __('Name', 'havnor-core') => 'name',
            __('Modified', 'havnor-core') => 'modified',
            __('Random', 'havnor-core') => 'rand',
            __('Comment Count', 'havnor-core') => 'comment_count',
          ),
          'param_name' => 'blog_orderby',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Show only certain categories?', 'havnor-core'),
          "param_name"  => "blog_show_category",
          "value"       => "",
          "description" => __( "Enter category SLUGS (comma separated) you want to display.", 'havnor-core')
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Short Content (Excerpt Length)', 'havnor-core'),
          "param_name"  => "short_content",
          "value"       => "",
          "description" => __( "Enter the numeric value of, how many words you want in short content paragraph.", 'havnor-core')
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Pagination', 'havnor-core'),
          "param_name"  => "blog_pagination",
          "value"       => "",
          "std"         => true,
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'param_name'      => 'blog_pagination_type',
          'type'    => 'dropdown',
          'heading'   => esc_html__('Blog Pagination Type', 'havnor-core'),
          'value'        => array(
            __( 'Select Pagination Type', 'havnor-core' ) => '',
            __( 'Ajax Infinite Scroll', 'havnor-core' ) => 'infinite-scroll',
            __( 'Ajax Button', 'havnor-core' ) => 'load-more',
            __( 'Navigation', 'havnor-core' ) => 'navigation',
          ),
          'dependency' => array(
            'element' => 'blog_pagination',
            'value' => 'true',
          ),
        ),
        array(
          'param_name' => 'load_more_btn_txt',
          'type'       => 'textfield',
          'heading'      => esc_html__('Load More Button Text', 'fraxos'),
          'dependency' => array(
            'element' => 'blog_pagination_type',
            'value' => 'load-more',
          ),
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Need Border for Blog infos', 'havnor-core'),
          "param_name"  => "need_border",
          "value"       => "",
          "std"         => false,
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>array('style-two','style-three'),
          ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Read More Button Text', 'havnor-core'),
          "param_name"  => "read_more_txt",
          "value"       => "",
          "description" => __( "Enter read more button text.", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        
        HavnorLib::vt_class_option(),
        // Carousel
        array(
          "type"        => "notice",
          "heading"     => 'Basic Options',
          "param_name"  => 'bsic_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Loop?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_loop",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          "description" => __( "Continuously moving carousel, if enabled.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Items", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_items",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how many items you want in per slide.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Margin", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_margin",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how much space you want between each carousel item.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Dots", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_dots",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Dots, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Navigation", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_nav",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Navigation, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Auto Play & Interaction',
          "param_name"  => 'apyi_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Autoplay Timeout", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay_timeout",
          'value' => '',
          "description" => __( "Change carousel Autoplay timing value. Default : 5000. Means 5 seconds.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Autoplay", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want to start Carousel automatically, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Animate Out", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_animate_out",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "CSS3 animation out.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Mouse Drag?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mousedrag",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want Mouse Drag, check it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Width & Height',
          "param_name"  => 'wah_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Width", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autowidth",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Width automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Height", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoheight",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Height automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Responsive Options',
          "param_name"  => 'res_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Tablet", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_tablet",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in tablet.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Small Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_small_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in small mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        // Styling
        array(
          "type" => "textfield",
          "heading" => __( "Section Title Size", 'havnor-core' ),
          "param_name" => "section_title_size",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Section Title Font Weight", 'havnor-core' ),
          "param_name" => "section_title_weight",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Section Title Bottom Space", 'havnor-core' ),
          "param_name" => "section_title_btm_space",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Section Title Color", 'havnor-core' ),
          "param_name" => "section_title_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Section Sub-Title Size", 'havnor-core' ),
          "param_name" => "section_sub_title_size",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Section Sub-Title Font Weight", 'havnor-core' ),
          "param_name" => "section_sub_title_weight",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Section Sub-Title Color", 'havnor-core' ),
          "param_name" => "section_sub_title_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-six',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Color", 'havnor-core' ),
          "param_name" => "blog_bg_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Hover Overlay Color", 'havnor-core' ),
          "param_name" => "bg_overlay_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Title Color", 'havnor-core' ),
          "param_name" => "title_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Title Hover Color", 'havnor-core' ),
          "param_name" => "title_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Content Color", 'havnor-core' ),
          "param_name" => "content_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Content Hover Color", 'havnor-core' ),
          "param_name" => "content_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Blog Meta Color", 'havnor-core' ),
          "param_name" => "blog_meta_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Blog Meta Hover Color", 'havnor-core' ),
          "param_name" => "blog_meta_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'blog_style',
            'value' =>'style-four',
          ),
        ),

      )
    ) );
  }
}
