<?php
/**
 * Stories - Shortcode Options
 */
add_action( 'init', 'havnor_stories_vc_map' );
if ( ! function_exists( 'havnor_stories_vc_map' ) ) {
  function havnor_stories_vc_map() {
    vc_map( array(
      "name" => __( "Stories", 'havnor-core'),
      "base" => "havnor_stories",
      "description" => __( "Stories Styles", 'havnor-core'),
      "icon" => "fa fa-history color-pink",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Stories Style', 'havnor-core' ),
          'value' => array(
            __( 'Style One (Grid)', 'havnor-core' )    => 'style-one',
            __( 'Style Two (Slider)', 'havnor-core' ) => 'style-two',
          ),
          'admin_label' => true,
          'param_name' => 'stories_style',
          'description' => __( 'Select your stories style.', 'havnor-core' ),
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Columns', 'havnor-core' ),
          'value' => array(
            __( 'Select Stories Columns', 'havnor-core' ) => '',
            __( 'Column Three', 'havnor-core' )  => 'col-3',
            __( 'Column Two', 'havnor-core' )    => 'col-2',
          ),
          'admin_label' => true,
          'param_name' => 'stories_column',
          'description' => __( 'Select your stories column.', 'havnor-core' ),
          'dependency' => array(
            'element' => 'stories_style',
            'value' => array('style-one'),
          ),
        ),
        array(
          'type' => 'textfield',
          'heading' => __( 'Image size', 'js_composer' ),
          'param_name' => 'img_size',
          'value' => '',
          'description' => __( 'Enter image size (Example: "thumbnail", "medium", "large", "full" or other sizes defined by theme). Alternatively enter size in pixels (Example: 200x100 (Width x Height)).', 'js_composer' ),
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Limit', 'havnor-core'),
          "param_name"  => "stories_limit",
          "value"       => "",
          'admin_label' => true,
          "description" => __( "Enter the number of items to show.", 'havnor-core'),
        ),
        array(
    			"type"        => "notice",
    			"heading"     => __( "Meta's to Hide", 'havnor-core' ),
    			"param_name"  => 'mts_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          "type"        => 'checkbox',
          "heading"     => __('Category', 'havnor-core'),
          "param_name"  => "stories_category",
          "value"       => "",
          "std"         => false,
          'edit_field_class' => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Date', 'havnor-core'),
          "param_name"  => "stories_date",
          "value"       => "",
          "std"         => false,
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Date Format', 'havnor-core'),
          "param_name"  => "date_format",
          "value"       => "",
          "description" => __( "Enter date format (for more info <a href='https://codex.wordpress.org/Formatting_Date_and_Time' target='_blank'>click here</a>).", 'havnor-core')
        ),
        array(
    			"type"        => "notice",
    			"heading"     => __( "Listing", 'havnor-core' ),
    			"param_name"  => 'lsng_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order', 'havnor-core' ),
          'value' => array(
            __( 'Select Stories Order', 'havnor-core' ) => '',
            __('Asending', 'havnor-core') => 'ASC',
            __('Desending', 'havnor-core') => 'DESC',
          ),
          'param_name' => 'stories_order',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order By', 'havnor-core' ),
          'value' => array(
            __('None', 'havnor-core') => 'none',
            __('ID', 'havnor-core') => 'ID',
            __('Author', 'havnor-core') => 'author',
            __('Title', 'havnor-core') => 'title',
            __('Date', 'havnor-core') => 'date',
          ),
          'param_name' => 'stories_orderby',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Show only certain ID?', 'havnor-core'),
          "param_name"  => "stories_post_in",
          "value"       => "",
          "description" => __( "Enter the ID (comma separated) you want to display.", 'havnor-core')
        ),
        HavnorLib::vt_class_option(),
        // Carousel
        array(
          "type"        => "notice",
          "heading"     => 'Basic Options',
          "param_name"  => 'bsic_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Loop?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_loop",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          "description" => __( "Continuously moving carousel, if enabled.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Items", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_items",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how many items you want in per slide.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Margin", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_margin",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how much space you want between each carousel item.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Dots", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_dots",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Dots, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Navigation", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_nav",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Navigation, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Auto Play & Interaction',
          "param_name"  => 'apyi_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Autoplay Timeout", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay_timeout",
          'value' => '',
          "description" => __( "Change carousel Autoplay timing value. Default : 5000. Means 5 seconds.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Autoplay", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want to start Carousel automatically, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Animate Out", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_animate_out",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "CSS3 animation out.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Mouse Drag?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mousedrag",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want Mouse Drag, check it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Width & Height',
          "param_name"  => 'wah_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Width", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autowidth",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Width automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Height", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoheight",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Height automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Responsive Options',
          "param_name"  => 'res_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Tablet", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_tablet",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in tablet.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Small Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_small_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in small mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'stories_style',
            'value' =>'style-two',
          ),
        ),
      )
    ) );
  }
}
