<?php
/**
 * Slider - Shortcode Options 
 */
add_action( 'init', 'slider_vc_map' );
if ( ! function_exists( 'slider_vc_map' ) ) {
  function slider_vc_map() {
    vc_map( array(
    "name" => __( "Slider", 'havnor-core'),
    "base" => "havnor_slider",
    "description" => __( "Slider Style", 'havnor-core'),
    "icon" => "fa fa-sliders color-pink",
    "category" => HavnorLib::havnor_cat_name(),
    "params" => array(   

      array(
        'type' => 'dropdown',
        'heading' => __( 'Slider Style', 'havnor-core' ),
        'value' => array(
          __( 'Style One', 'havnor-core' ) => 'one',
          __( 'Static Banner', 'havnor-core' ) => 'three',
        ),
        'param_name' => 'slider_style',
        'description' => __( 'Select slider style.', 'havnor-core' ),
        'admin_label' => true,
      ), 
      array(
        'type' => 'dropdown',
        'heading' => __( 'Banner Style', 'havnor-core' ),
        'value' => array(
          __( 'Select Banner Style', 'havnor-core' ) => '',
          __( 'Style One', 'havnor-core' ) => 'ban-one',
          __( 'Style Two', 'havnor-core' ) => 'ban-two',
        ),
        'param_name' => 'banner_style',
        'description' => __( 'Select banner style.', 'havnor-core' ),
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ), 
      array(
        "type" => "checkbox",
        "heading" => __( "Need Particles for Banner?", 'havnor-core' ),
        "param_name" => "need_particles",
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        'type' => 'dropdown',
        'heading' => __( 'Banner Content Alignment', 'havnor-core' ),
        'value' => array(
          __( 'Select Banner Content Align', 'havnor-core' ) => '',
          __( 'Left', 'havnor-core' ) => 'left',
          __( 'Right', 'havnor-core' ) => 'right',
          __( 'Center', 'havnor-core' ) => 'center',
        ),
        'param_name' => 'banner_align',
        'description' => __( 'Select banner content align.', 'havnor-core' ),
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ), 
      array(
        'type' => 'attach_image',
        'value' => '',
        'heading' => __( 'Upload Background Image', 'havnor-core' ),
        'param_name' => 'static_image',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        "type"        => "notice",
        "heading"     => __( "Banner Content", 'havnor-core' ),
        "param_name"  => 'lsd',
        'class'       => 'cs-success',
        'value'       => '',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        'type' => 'textfield',
        'value' => '',
        'heading' => __( 'Banner Title', 'havnor-core' ),
        'admin_label' => true,
        'param_name' => 'static_slider_title',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        'type' => 'textarea',
        'value' => '',
        'heading' => __( 'Banner Content', 'havnor-core' ),
        'param_name' => 'static_slider_content',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        'type' => 'textarea_html',
        'value' => '',
        'heading' => __( 'Banner Content(Additional Shortcodes)', 'havnor-core' ),
        'param_name' => 'content',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        'type' => 'dropdown',
        'heading' => __( 'Button Style', 'havnor-core' ),
        'value' => array(
          __( 'Select Button Style', 'havnor-core' ) => '',
          __( 'Style One', 'havnor-core' ) => 'bs-one',
          __( 'Style Two', 'havnor-core' ) => 'bs-two',
        ),
        'param_name' => 'button_style',
        'description' => __( 'Select button style.', 'havnor-core' ),
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ), 
      array(
        'type' => 'textfield',
        'value' => '',
        'heading' => __( 'Link Text', 'havnor-core' ),
        'param_name' => 'link_text',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        'type' => 'textfield',
        'value' => '',
        'heading' => __( 'Button Link', 'havnor-core' ),
        'param_name' => 'text_link',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        "type"      => 'vt_icon',
        "heading"   => __('Set Icon', 'havnor-core'),
        "param_name" => "icon",
        "value"      => "",
        "description" => __( "Set your video icon.", 'havnor-core'),
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'three',
        ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Need Navigation Arrow?", 'havnor-core' ),
        "param_name" => "need_nav",
        "std" => true,
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Need Navigation Dots?", 'havnor-core' ),
        "param_name" => "need_dot",
        "std" => true,
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      HavnorLib::vt_open_link_tab(),
      havnorLib::vt_class_option(),
      // List
      array(
        'type' => 'param_group', 
        'value' => '',
        'heading' => __( 'Slider', 'havnor-core' ),
        'param_name' => 'sliders',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
        // Note params is mapped inside param-group:
        'params' => array(      
          array(
            'type' => 'attach_image',
            'value' => '',
            'heading' => __( 'Upload Background Image', 'havnor-core' ),
            'param_name' => 'slider_image',
            'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Caption Alignment', 'havnor-core' ),
            'value' => array(
              __( 'Select The Alignment', 'havnor-core' ) => '',
              __( 'Left', 'havnor-core' ) => 'left',
              __( 'Right', 'havnor-core' ) => 'right',
              __( 'Center', 'havnor-core' ) => 'center',
            ),
            'param_name' => 'caption_alignment',
            'description' => __( 'Select your alignment.', 'havnor-core' ),
            'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          ),            
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Slider Title', 'havnor-core' ),
            'admin_label' => true,
            'param_name' => 'slider_title',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Title Animation', 'havnor-core' ),
            'value' => array(
              __( 'fadeInDown', 'havnor-core' )          => 'fadeInDown',
              __( 'bounce', 'havnor-core' )              => 'bounce',
              __( 'flash', 'havnor-core' )               => 'flash',
              __( 'pulse', 'havnor-core' )               => 'pulse',
              __( 'rubberBand', 'havnor-core' )          => 'rubberBand',
              __( 'shake', 'havnor-core' )               => 'shake',
              __( 'swing', 'havnor-core' )               => 'swing',
              __( 'tada', 'havnor-core' )                => 'tada',
              __( 'wobble', 'havnor-core' )              => 'wobble',
              __( 'jello', 'havnor-core' )               => 'jello',
              __( 'bounceIn', 'havnor-core' )            => 'bounceIn',
              __( 'bounceInDown', 'havnor-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'havnor-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'havnor-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'havnor-core' )          => 'bounceInUp',
              __( 'bounceOut', 'havnor-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'havnor-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'havnor-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'havnor-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'havnor-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'havnor-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'havnor-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'havnor-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'havnor-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'havnor-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'havnor-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'havnor-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'havnor-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'havnor-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'havnor-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'havnor-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'havnor-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'havnor-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'havnor-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'havnor-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'havnor-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'havnor-core' )        => 'fadeOutUpBig',
              __( 'flip', 'havnor-core' )                => 'flip',
              __( 'flipInX', 'havnor-core' )             => 'flipInX',
              __( 'flipInY', 'havnor-core' )             => 'flipInY',
              __( 'flipOutX', 'havnor-core' )            => 'flipOutX',
              __( 'flipOutY', 'havnor-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'havnor-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'havnor-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'havnor-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'havnor-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'havnor-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'havnor-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'havnor-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'havnor-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'havnor-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'havnor-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'havnor-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'havnor-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'havnor-core' )           => 'slideInUp',
              __( 'slideInDown', 'havnor-core' )         => 'slideInDown',
              __( 'slideInLeft', 'havnor-core' )         => 'slideInLeft',
              __( 'slideInRight', 'havnor-core' )        => 'slideInRight',
              __( 'slideOutUp', 'havnor-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'havnor-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'havnor-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'havnor-core' )       => 'slideOutRight',
              __( 'zoomIn', 'havnor-core' )              => 'zoomIn',
              __( 'zoomInDown', 'havnor-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'havnor-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'havnor-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'havnor-core' )            => 'zoomInUp',
              __( 'zoomOut', 'havnor-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'havnor-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'havnor-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'havnor-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'havnor-core' )           => 'zoomOutUp',
              __( 'hinge', 'havnor-core' )               => 'hinge',
              __( 'jackInTheBox', 'havnor-core' )        => 'jackInTheBox',
              __( 'rollIn', 'havnor-core' )              => 'rollIn',
              __( 'rollOut', 'havnor-core' )             => 'rollOut',
            ),
            'param_name' => 'title_animation',
            'description' => __( 'Select your title animation.', 'havnor-core' ),
          ),  
          array(
            'type' => 'textarea',
            'value' => '',
            'heading' => __( 'Slider Content', 'havnor-core' ),
            'param_name' => 'slider_content',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Content Animation', 'havnor-core' ),
            'value' => array(
              __( 'fadeInDown', 'havnor-core' )          => 'fadeInDown',
              __( 'bounce', 'havnor-core' )              => 'bounce',
              __( 'flash', 'havnor-core' )               => 'flash',
              __( 'pulse', 'havnor-core' )               => 'pulse',
              __( 'rubberBand', 'havnor-core' )          => 'rubberBand',
              __( 'shake', 'havnor-core' )               => 'shake',
              __( 'swing', 'havnor-core' )               => 'swing',
              __( 'tada', 'havnor-core' )                => 'tada',
              __( 'wobble', 'havnor-core' )              => 'wobble',
              __( 'jello', 'havnor-core' )               => 'jello',
              __( 'bounceIn', 'havnor-core' )            => 'bounceIn',
              __( 'bounceInDown', 'havnor-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'havnor-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'havnor-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'havnor-core' )          => 'bounceInUp',
              __( 'bounceOut', 'havnor-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'havnor-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'havnor-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'havnor-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'havnor-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'havnor-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'havnor-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'havnor-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'havnor-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'havnor-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'havnor-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'havnor-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'havnor-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'havnor-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'havnor-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'havnor-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'havnor-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'havnor-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'havnor-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'havnor-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'havnor-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'havnor-core' )        => 'fadeOutUpBig',
              __( 'flip', 'havnor-core' )                => 'flip',
              __( 'flipInX', 'havnor-core' )             => 'flipInX',
              __( 'flipInY', 'havnor-core' )             => 'flipInY',
              __( 'flipOutX', 'havnor-core' )            => 'flipOutX',
              __( 'flipOutY', 'havnor-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'havnor-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'havnor-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'havnor-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'havnor-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'havnor-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'havnor-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'havnor-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'havnor-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'havnor-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'havnor-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'havnor-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'havnor-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'havnor-core' )           => 'slideInUp',
              __( 'slideInDown', 'havnor-core' )         => 'slideInDown',
              __( 'slideInLeft', 'havnor-core' )         => 'slideInLeft',
              __( 'slideInRight', 'havnor-core' )        => 'slideInRight',
              __( 'slideOutUp', 'havnor-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'havnor-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'havnor-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'havnor-core' )       => 'slideOutRight',
              __( 'zoomIn', 'havnor-core' )              => 'zoomIn',
              __( 'zoomInDown', 'havnor-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'havnor-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'havnor-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'havnor-core' )            => 'zoomInUp',
              __( 'zoomOut', 'havnor-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'havnor-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'havnor-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'havnor-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'havnor-core' )           => 'zoomOutUp',
              __( 'hinge', 'havnor-core' )               => 'hinge',
              __( 'jackInTheBox', 'havnor-core' )        => 'jackInTheBox',
              __( 'rollIn', 'havnor-core' )              => 'rollIn',
              __( 'rollOut', 'havnor-core' )             => 'rollOut',
            ),
            'param_name' => 'content_animation',
            'description' => __( 'Select your content animation.', 'havnor-core' ),
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button Text', 'havnor-core' ),
            'param_name' => 'slider_bone_text',
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button Link', 'havnor-core' ),
            'param_name' => 'slider_bone_link',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Button Animation', 'havnor-core' ),
            'value' => array(
              __( 'fadeInDown', 'havnor-core' )          => 'fadeInDown',
              __( 'bounce', 'havnor-core' )              => 'bounce',
              __( 'flash', 'havnor-core' )               => 'flash',
              __( 'pulse', 'havnor-core' )               => 'pulse',
              __( 'rubberBand', 'havnor-core' )          => 'rubberBand',
              __( 'shake', 'havnor-core' )               => 'shake',
              __( 'swing', 'havnor-core' )               => 'swing',
              __( 'tada', 'havnor-core' )                => 'tada',
              __( 'wobble', 'havnor-core' )              => 'wobble',
              __( 'jello', 'havnor-core' )               => 'jello',
              __( 'bounceIn', 'havnor-core' )            => 'bounceIn',
              __( 'bounceInDown', 'havnor-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'havnor-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'havnor-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'havnor-core' )          => 'bounceInUp',
              __( 'bounceOut', 'havnor-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'havnor-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'havnor-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'havnor-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'havnor-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'havnor-core' )              => 'fadeIn',              
              __( 'fadeInDownBig', 'havnor-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'havnor-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'havnor-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'havnor-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'havnor-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'havnor-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'havnor-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'havnor-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'havnor-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'havnor-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'havnor-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'havnor-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'havnor-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'havnor-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'havnor-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'havnor-core' )        => 'fadeOutUpBig',
              __( 'flip', 'havnor-core' )                => 'flip',
              __( 'flipInX', 'havnor-core' )             => 'flipInX',
              __( 'flipInY', 'havnor-core' )             => 'flipInY',
              __( 'flipOutX', 'havnor-core' )            => 'flipOutX',
              __( 'flipOutY', 'havnor-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'havnor-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'havnor-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'havnor-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'havnor-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'havnor-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'havnor-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'havnor-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'havnor-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'havnor-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'havnor-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'havnor-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'havnor-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'havnor-core' )           => 'slideInUp',
              __( 'slideInDown', 'havnor-core' )         => 'slideInDown',
              __( 'slideInLeft', 'havnor-core' )         => 'slideInLeft',
              __( 'slideInRight', 'havnor-core' )        => 'slideInRight',
              __( 'slideOutUp', 'havnor-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'havnor-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'havnor-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'havnor-core' )       => 'slideOutRight',
              __( 'zoomIn', 'havnor-core' )              => 'zoomIn',
              __( 'zoomInDown', 'havnor-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'havnor-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'havnor-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'havnor-core' )            => 'zoomInUp',
              __( 'zoomOut', 'havnor-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'havnor-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'havnor-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'havnor-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'havnor-core' )           => 'zoomOutUp',
              __( 'hinge', 'havnor-core' )               => 'hinge',
              __( 'jackInTheBox', 'havnor-core' )        => 'jackInTheBox',
              __( 'rollIn', 'havnor-core' )              => 'rollIn',
              __( 'rollOut', 'havnor-core' )             => 'rollOut',
            ),
            'param_name' => 'btn_animation',
            'description' => __( 'Select your button animation.', 'havnor-core' ),
          ),
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Custom Class', 'havnor-core' ),
            'param_name' => 'custom_class',
          ),    
        ),
        
      ),

      // Particle Options
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Particle Dot Color', 'havnor-core'),
        "param_name"  => "particle_dot_color",
        "value"       => "",
        "group"       => __('Particle', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'need_particles',
          'value' => 'true',
        ),
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Particle Line Color', 'havnor-core'),
        "param_name"  => "particle_line_color",
        "value"       => "",
        "group"       => __('Particle', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'need_particles',
          'value' => 'true',
        ),
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Dot Count', 'havnor-core'),
        "param_name"  => "dot_count",
        "value"       => "",
        "group"       => __('Particle', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'need_particles',
          'value' => 'true',
        ),
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Speed', 'havnor-core'),
        "param_name"  => "dot_speed",
        "value"       => "",
        "group"       => __('Particle', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'need_particles',
          'value' => 'true',
        ),
      ),

      // Slider Options
      array(
        'type' => 'dropdown',
        'heading' => __( 'Slider Transition Effect', 'havnor-core' ),
        'value' => array(
          __( 'Slide', 'havnor-core' ) => 'slide',
          __( 'Fade', 'havnor-core' ) => 'fade',
          __( 'Cube', 'havnor-core' ) => 'cube',
          __( 'Coverflow', 'havnor-core' ) => 'coverflow',
        ),
        'param_name' => 'slider_effect',
        "group"       => __('Slider', 'havnor-core'),
        'description' => __( 'Select slider effect.', 'havnor-core' ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Loop?", 'havnor-core' ),
        "param_name" => "enable_loop",
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Autoplay?", 'havnor-core' ),
        "param_name" => "autoplay",
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Disable Autoplay on interaction?", 'havnor-core' ),
        "param_name" => "disable_on_interaction",
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Enable Mousedrag?", 'havnor-core' ),
        "param_name" => "mousedrag",
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type" => "checkbox",
        "heading" => __( "Pagination Dots Clickable?", 'havnor-core' ),
        "param_name" => "clickable_pagi",
        'value' => '',
        "on_text" => __( "Yes", 'havnor-core' ),
        "off_text" => __( "No", 'havnor-core' ),
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'  => 'vc_col-md-4 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Autoplay Timeout', 'havnor-core'),
        "param_name"  => "autoplay_time",
        "value"       => "",
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Speed', 'havnor-core'),
        "param_name"  => "autoplay_speed",
        "value"       => "",
        "group"       => __('Slider', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'slider_style',
          'value' => 'one',
        ),
      ),
      // Style      
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Caption Overlay Color', 'havnor-core'),
        "param_name"  => "caption_overlay",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Title Color', 'havnor-core'),
        "param_name"  => "title_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Content Color', 'havnor-core'),
        "param_name"  => "content_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
      ),
      array(
        "type"        => "notice",
        "heading"     => __( "Button Option", 'havnor-core' ),
        "param_name"  => 'bone',
        'class'       => 'cs-success',
        'value'       => '',
        "group"       => __('Style', 'havnor-core'),
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Text Color', 'havnor-core'),
        "param_name"  => "bone_text_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Text Hover Color', 'havnor-core'),
        "param_name"  => "bone_text_hover_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Background Color', 'havnor-core'),
        "param_name"  => "bone_bg_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Background Hover Color', 'havnor-core'),
        "param_name"  => "bone_bg_hover_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Border Color', 'havnor-core'),
        "param_name"  => "bone_border_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Border Hover Color', 'havnor-core'),
        "param_name"  => "bone_border_hover_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      
      // Size
      array(
        "type"        =>'textfield',
        "heading"     =>__('Title Text Size', 'havnor-core'),
        "param_name"  => "title_size",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Title Font Weight', 'havnor-core'),
        "param_name"  => "title_weight",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Title Line Height', 'havnor-core'),
        "param_name"  => "title_line_height",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Title Bottom Space', 'havnor-core'),
        "param_name"  => "title_bottom_space",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Content Text Size', 'havnor-core'),
        "param_name"  => "content_size",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Content Font Weight', 'havnor-core'),
        "param_name"  => "content_weight",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Content Line Height', 'havnor-core'),
        "param_name"  => "content_line_height",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Content Bottom Space', 'havnor-core'),
        "param_name"  => "content_btm_space",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Button Text Size', 'havnor-core'),
        "param_name"  => "bone_text_size",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Button Border Radius', 'havnor-core'),
        "param_name"  => "bone_border_radius",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Button Top Space', 'havnor-core'),
        "param_name"  => "bone_top_space",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Button Bottom Space', 'havnor-core'),
        "param_name"  => "bone_bottom_space",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Link Text Size', 'havnor-core'),
        "param_name"  => "link_text_size",
        "value"       => "",
        "group"       => __('Size', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'button_style',
          'value' => array('bs-two'),
        ),
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Link Color', 'havnor-core'),
        "param_name"  => "link_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'button_style',
          'value' => array('bs-two'),
        ),
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Link Hover Color', 'havnor-core'),
        "param_name"  => "link_hover_color",
        "value"       => "",
        "group"       => __('Style', 'havnor-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        'dependency' => array(
          'element' => 'button_style',
          'value' => array('bs-two'),
        ),
      ),

      ), // Params
    ) );
  }
}
