<?php
/**
 * Client Carousel - Shortcode Options
 */
add_action( 'init', 'featured_content_vc_map' );
if ( ! function_exists( 'featured_content_vc_map' ) ) {
  function featured_content_vc_map() {
    vc_map( array(
      "name" => __( "Featured Content", 'havnor-core'),
      "base" => "hanor_featured_content",
      "description" => __( "Featured Content Section", 'havnor-core'),
      "icon" => "fa fa-shield color-red",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Featured Style', 'havnor-core' ),
          'value' => array(
            __( 'Featured Style One', 'havnor-core' ) => 'featured-one',
            __( 'Featured Style Two (Slider)', 'havnor-core' ) => 'featured-two',
          ),
          'admin_label' => true,
          'param_name' => 'featured_style',
          'description' => __( 'Select your featured style.', 'havnor-core' ),
        ),
        array(
          'type' => 'attach_image',
          'value' => '',
          'heading' => __( 'Upload Banner Image', 'havnor-core' ),
          'param_name' => 'select_image',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Section Title", 'havnor-core' ),
          "param_name" => "title_text",
          'value' => '',
          'admin_label' => true,
          "description" => __( "Enter your section title.", 'havnor-core'),
           'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textarea",
          "heading" => __( "Section Content", 'havnor-core' ),
          "param_name" => "content_text",
          'value' => '',
          'admin_label' => true,
          "description" => __( "Enter your section content.", 'havnor-core'),
           'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Text", 'havnor-core' ),
          "param_name" => "btn_text",
          'value' => '',
          "description" => __( "Enter your button text.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
           'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Link", 'havnor-core' ),
          "param_name" => "btn_link",
          'value' => '',
          "description" => __( "Enter your button link.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
           'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        HavnorLib::vt_open_link_tab(),
        // Client Logos
        array(
          'type' => 'param_group',
          'value' => '',
          'heading' => __( 'Featured Sections', 'havnor-core' ),
          'param_name' => 'featured_images',
          // Note params is mapped inside param-group:
          'params' => array(
            array(
              'type' => 'attach_image',
              'value' => '',
              "admin_label"=> true,
              'heading' => __( 'Upload Image', 'havnor-core' ),
              'param_name' => 'featured_image',
            ),
            array(
              'type' => 'textfield',
              'value' => '',
              'heading' => __( 'Title', 'havnor-core' ),
              'param_name' => 'title_feature',
            ),
            array(
              'type' => 'textfield',
              'value' => '',
              'heading' => __( 'Title Link', 'havnor-core' ),
              'param_name' => 'title_link',
            ),
            array(
              'type' => 'textarea',
              'value' => '',
              'heading' => __( 'Feature Content', 'havnor-core' ),
              'param_name' => 'feature_content',
              'dependency' => array(
                'element' => 'featured_style',
                'value' => 'featured-two',
              ),
            )
          ) 
        ), 
        // Title
        HavnorLib::vt_notice_field(__( "Title & Content Styling", 'havnor-core' ),'tle_opt','cs-warning', 'Styling'), // Notice
        array(
          "type" => "colorpicker",
          "heading" => __( "Banner Image Overlay Color", 'havnor-core' ),
          "param_name" => "banner_overlay_color",
          'value' => '',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Info Background Color", 'havnor-core' ),
          "param_name" => "info_bg_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Title Color", 'havnor-core' ),
          "param_name" => "title_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Title Size", 'havnor-core' ),
          "param_name" => "title_size",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ), 
        array(
          "type" => "colorpicker",
          "heading" => __( "Title Link Hover Color", 'havnor-core' ),
          "param_name" => "title_link_hover_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
        ),
         // Content 
        array(
          "type" => "colorpicker",
          "heading" => __( "Content Color", 'havnor-core' ),
          "param_name" => "content_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Content Size", 'havnor-core' ),
          "param_name" => "content_size",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
           'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Section Background Color", 'havnor-core' ),
          "param_name" => "section_bg_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
           'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Left Side Section Styling',
          "param_name"  => 'tle_opt',
          'class'       => 'cs-success',
          'value'       => '',
          "group"       => 'Styling',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Title Styling',
          "param_name"  => 'tle_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Styling',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Title Text Size", 'havnor-core' ),
          "param_name" => "title_text_size",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Title Line Height", 'havnor-core' ),
          "param_name" => "title_line_height",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Title Text Color", 'havnor-core' ),
          "param_name" => "title_text_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Description Styling',
          "param_name"  => 'tle_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Styling',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Description Text Size", 'havnor-core' ),
          "param_name" => "desc_text_size",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Description Line Height", 'havnor-core' ),
          "param_name" => "desc_line_height",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Description Text Color", 'havnor-core' ),
          "param_name" => "desc_text_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Button Styling',
          "param_name"  => 'tle_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Styling',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Text Size", 'havnor-core' ),
          "param_name" => "btn_text_size",
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Border Radius", 'havnor-core' ),
          "param_name" => "border_radius",
          'value' => '',
          "description" => __( "Enter button border radius. [Eg: 14px]", 'havnor-core'),
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Text Color", 'havnor-core' ),
          "param_name" => "btn_text_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Text Hover Color", 'havnor-core' ),
          "param_name" => "btn_text_hover_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Background Color", 'havnor-core' ),
          "param_name" => "btn_bg_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Background Hover Color", 'havnor-core' ),
          "param_name" => "btn_bg_hover_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Border Color", 'havnor-core' ),
          "param_name" => "btn_border_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
            'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Border Hover Color", 'havnor-core' ),
          "param_name" => "btn_border_hover_color",
          'value' => '',
          "group" => __( "Styling", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        HavnorLib::vt_class_option(),
        // Carousel
        array(
          "type" => "checkbox",
          "heading" => __( "Loop?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_loop",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          "description" => __( "Continuously moving carousel, if enabled.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Items", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_items",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how many items you want in per slide.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Margin", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_margin",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how much space you want between each carousel item.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Dots", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_dots",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Dots, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Navigation", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_nav",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Navigation, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Auto Play & Interaction',
          "param_name"  => 'apyi_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Autoplay Timeout", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay_timeout",
          'value' => '',
          "description" => __( "Change carousel Autoplay timing value. Default : 5000. Means 5 seconds.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Autoplay", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want to start Carousel automatically, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Animate Out", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_animate_out",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "CSS3 animation out.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Mouse Drag?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mousedrag",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want Mouse Drag, check it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Width & Height',
          "param_name"  => 'wah_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Width", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autowidth",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Width automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Height", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoheight",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Height automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Responsive Options',
          "param_name"  => 'res_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Tablet", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_tablet",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in tablet.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Small Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_small_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in small mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'featured_style',
            'value' => 'featured-two',
          ),
        ),

      )
    ) );
  }
}
