<?php
/**
 * Forms - Shortcode Options
 */
add_action( 'init', 'havnor_forms_vc_map' );
if ( ! function_exists( 'havnor_forms_vc_map' ) ) {
  function havnor_forms_vc_map() {
    vc_map( array(
      "name" => __( "Forms", 'havnor-core'),
      "base" => "hanor_forms",
      "description" => __( "Forms Styles", 'havnor-core'),
      "icon" => "fa fa-wpforms color-green",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Forms Style', 'havnor-core' ),
          'value' => array(
            __( 'Style One', 'havnor-core' ) => 'form-one',
            __( 'Style Two', 'havnor-core' ) => 'form-two',
            __( 'Style Three', 'havnor-core' ) => 'form-three',
            __( 'Style Four', 'havnor-core' ) => 'form-four',
            __( 'Style Five', 'havnor-core' ) => 'form-five',
          ),
          'admin_label' => true,
          'param_name' => 'forms_style',
          'description' => __( 'Select your form style.', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Form Title', 'havnor-core' ),
          'param_name' => 'forms_title',
          'admin_label' => true,
        ),
        array(
          'type' => 'textarea',
          'value' => '',
          'heading' => __( 'Form Content', 'havnor-core' ),
          'param_name' => 'forms_content',
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Alert Text', 'havnor-core' ),
          'param_name' => 'alert',
        ),
        array(
          'type' => 'textarea_html',
          'value' => '',
          'heading' => __( 'Forms', 'havnor-core' ),
          'param_name' => 'content',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-one', 'form-two', 'form-four'),
          ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Login Text', 'havnor-core' ),
          'param_name' => 'login_text',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-five'),
          ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Login Link', 'havnor-core' ),
          'param_name' => 'login_link',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-five'),
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Open New Tab?", 'havnor-core' ),
          "param_name" => "open_link",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-five'),
          ),
        ),

        HavnorLib::vt_class_option(),
        // Style
        array(
          "type"        => "notice",
          "heading"     => 'Content Styles',
          "param_name"  => 'content_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Form Background Color', 'havnor-core' ),
          'param_name' => 'form_three_bg_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Title Color', 'havnor-core' ),
          'param_name' => 'title_color',
          'group' => __( 'Style', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'description' => __( 'Pick your title color.', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Title Size', 'havnor-core' ),
          'param_name' => 'title_size',
          'group' => __( 'Style', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'description' => __( 'Enter the px value if you used title area in forms style type one.', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Title Font Weight', 'havnor-core' ),
          'param_name' => 'title_weight',
          'group' => __( 'Style', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'description' => __( 'Enter the font weight for title.', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Title Bottom Space', 'havnor-core' ),
          'param_name' => 'title_bottom_space',
          'group' => __( 'Style', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'description' => __( 'Enter the title bottom space.', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Text Color', 'havnor-core' ),
          'param_name' => 'text_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Text Size', 'havnor-core' ),
          'param_name' => 'text_size',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Content Font Weight', 'havnor-core' ),
          'param_name' => 'content_weight',
          'group' => __( 'Style', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'description' => __( 'Enter the font weight for content.', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Content Bottom Space', 'havnor-core' ),
          'param_name' => 'content_bottom_space',
          'group' => __( 'Style', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'description' => __( 'Enter the content bottom space.', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Alter Text Color', 'havnor-core' ),
          'param_name' => 'alter_text_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Icon Styles',
          "param_name"  => 'icon_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-four','form-two','form-one'),
          ),
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Icon Color', 'havnor-core' ),
          'param_name' => 'icon_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-four','form-two','form-one'),
          ),
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'textfield',
          'value' => '',
          'heading' => __( 'Icon Size', 'havnor-core' ),
          'param_name' => 'icon_size',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-four','form-two','form-one'),
          ),
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Icon Hover Color', 'havnor-core' ),
          'param_name' => 'icon_hover_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-four','form-two','form-one'),
          ),
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Button Styles',
          "param_name"  => 'btn_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Button Background Color', 'havnor-core' ),
          'param_name' => 'button_bg_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Button Background Hover Color', 'havnor-core' ),
          'param_name' => 'button_bg_hover_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Button Text Color', 'havnor-core' ),
          'param_name' => 'button_text_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Button Text Hover Color', 'havnor-core' ),
          'param_name' => 'button_text_hover_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Button Border Color', 'havnor-core' ),
          'param_name' => 'button_border_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Button Border Hover Color', 'havnor-core' ),
          'param_name' => 'button_border_hover_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Background Styles',
          "param_name"  => 'bg_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-one'),
          ),
          'group' => __( 'Style', 'havnor-core' ),
        ),
        array(
          'type' => 'colorpicker',
          'value' => '',
          'heading' => __( 'Form Background Color', 'havnor-core' ),
          'param_name' => 'from_bg_color',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'group' => __( 'Style', 'havnor-core' ),
          'dependency' => array(
            'element' => 'forms_style',
            'value' => array('form-one'),
          ),
          'description' => __( 'Pick background color for <strong>Subscribe form</strong>.', 'havnor-core' ),
        ),

      )
    ) );
  }
}
