<?php
/**
 * Services - Shortcode Options
 */
add_action( 'init', 'havnor_services_vc_map' );
if ( ! function_exists( 'havnor_services_vc_map' ) ) {
  function havnor_services_vc_map() {
    vc_map( array(
      "name" => __( "Service", 'havnor-core'),
      "base" => "hanor_services",
      "description" => __( "Service Shortcodes", 'havnor-core'),
      "icon" => "fa fa-cog color-brown",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Services Style', 'havnor-core' ),
          'value' => array(
            __( 'Style One', 'havnor-core' ) => 'service-one',
            __( 'Style Two', 'havnor-core' ) => 'service-two',
            __( 'Style Three', 'havnor-core' ) => 'service-three',
            __( 'Style Four', 'havnor-core' ) => 'service-four',
            __( 'Style Five', 'havnor-core' ) => 'service-five',
          ),
          'admin_label' => true,
          'param_name' => 'service_style',
          'description' => __( 'Select your service style.', 'havnor-core' ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Stunning Services?", 'havnor-core' ),
          "param_name" => "stunnhing_services",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => array('service-one'),
          ),
        ),
        HavnorLib::vt_open_link_tab(),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Section Align', 'havnor-core' ),
          'value' => array(
            __( 'Center Align', 'havnor-core' ) => 'center',
            __( 'Right Align', 'havnor-core' ) => 'right',
            __( 'Left Align', 'havnor-core' ) => 'left',
          ),
          'param_name' => 'text_align_style',
          'description' => __( 'Select content alignment style.', 'havnor-core' ),
            'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-five',
          ),
        ),
        array(
          "type"      => 'attach_image',
          "heading"   => __('Upload Service Background Image', 'havnor-core'),
          "param_name" => "service_bg_image",
          "value"      => "",
          "description" => __( "Set your service background image.", 'havnor-core'),
          'dependency' => array(
            'element' => 'service_style',
            'value' => array('service-four','service-one'),
          ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Need Icon or Image ?', 'havnor-core' ),
           "param_name" => "image_icon",
          'value' => array(
            __( 'Image', 'havnor-core' ) => 'image-tab',
            __( 'Icon', 'havnor-core' ) => 'icon-tab',
          ),
        ),
        array(
          "type"      => 'attach_image',
          "heading"   => __('Upload Service Image', 'havnor-core'),
          "param_name" => "service_image",
          "value"      => "",
          "description" => __( "Set your service image.", 'havnor-core'),
          'dependency' => array(
            'element' => 'image_icon',
            'value' => 'image-tab',
          ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'vt_icon',
          "heading"   => __('Upload Icon', 'havnor-core'),
          "param_name" => "service_icon",
          "value"      => "",
          "description" => __( "Set your service icon image.", 'havnor-core'),
          'dependency' => array(
            'element' => 'image_icon',
            'value' => 'icon-tab',
          ),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Image Link', 'havnor-core'),
          "param_name" => "service_image_link",
          "value"      => "",
          "description" => __( "Enter your service image link.(This Link will apply only for image)", 'havnor-core'),
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-one',
          ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        HavnorLib::vt_notice_field(__( "Content Area", 'havnor-core' ),'cntara_opt','cs-warning', ''), // Notice
        array(
          "type"      => 'vc_link',
          "heading"   => __('Service Title', 'havnor-core'),
          "param_name" => "service_title",
          "value"      => "",
          "description" => __( "Enter your service title and link.", 'havnor-core')
        ),
        array(
          "type"      => 'textarea_html',
          "heading"   => __('Content', 'havnor-core'),
          "param_name" => "content",
          "value"      => "",
          "description" => __( "Enter your service content here.", 'havnor-core')
        ),
        // Read More
        array(
    			"type"        => "notice",
    			"heading"     => __( "Read More Link", 'havnor-core' ),
    			"param_name"  => 'rml_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
    		),
        array(
          "type"      => 'textfield',
          "heading"   => __('Link', 'havnor-core'),
          "param_name" => "read_more_link",
          "value"      => "",
          "description" => __( "Set your link for read more.", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title', 'havnor-core'),
          "param_name" => "read_more_title",
          "value"      => "",
          "description" => __( "Enter your read more title.", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Need Border", 'havnor-core' ),
          "param_name" => "services_border",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Need border for service section ?", 'havnor-core'),
          'dependency' => array(
            'element' => 'service_style',
            'value' => array('service-five'),
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Need Dropshadow", 'havnor-core' ),
          "param_name" => "services_dropshadow",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Need drop shadow for service section ?", 'havnor-core'),
          'dependency' => array(
            'element' => 'service_style',
            'value' => array('service-five'),
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Need Border Radius", 'havnor-core' ),
          "param_name" => "services_border_radius",
          "std" => false,
          'value' => '',
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Need border radius for service section?", 'havnor-core'),
          'dependency' => array(
            'element' => 'service_style',
            'value' => array('service-five'),
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Text", 'havnor-core' ),
          "param_name" => "btn_text",
          'value' => '',
          "description" => __( "Enter your button text.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
           'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-five',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Link", 'havnor-core' ),
          "param_name" => "btn_link",
          'value' => '',
          "description" => __( "Enter your button link.", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-five',
          ),
        ),
    
        HavnorLib::vt_class_option(),

        // Style
        array(
          "type" => "colorpicker",
          "heading" => __( "Background Image Overlay Color", 'havnor-core' ),
          "param_name" => "background_overlay_color",
          'value' => '',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-four',
          ),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        HavnorLib::vt_notice_field(__( "Title Styling", 'havnor-core' ),'tle_opt','cs-warning', 'Style'), // Notice
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Title Color', 'havnor-core'),
          "param_name" => "title_color",
          "value"      => "",
          "description" => __( "Pick your heading color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Size', 'havnor-core'),
          "param_name" => "title_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for title size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Title Hover Color', 'havnor-core'),
          "param_name" => "title_hover_color",
          "value"      => "",
          "description" => __( "Pick your heading hover color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Title Font Weight', 'havnor-core'),
          "param_name" => "title_weight",
          "value"      => "",
          "description" => __( "Enter the numeric value for title font weight.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        HavnorLib::vt_notice_field(__( "Content Styling", 'havnor-core' ),'cnt_opt','cs-warning', 'Style'), // Notice
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Content Color', 'havnor-core'),
          "param_name" => "content_color",
          "value"      => "",
          "description" => __( "Pick your content color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Content Size', 'havnor-core'),
          "param_name" => "content_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for content size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        HavnorLib::vt_notice_field(__( "Icon Styling", 'havnor-core' ),'icn_opt','cs-warning', 'Style'), // Notice
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Icon Color', 'havnor-core'),
          "param_name" => "icon_color",
          "value"      => "",
          "description" => __( "Pick your icon color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Icon Size', 'havnor-core'),
          "param_name" => "icon_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for icon size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Read More Styling',
          "param_name"  => 'rmre_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group" => __( "Style", 'havnor-core'),
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Link Color', 'havnor-core'),
          "param_name" => "link_color",
          "value"      => "",
          "description" => __( "Pick your link color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
        ),
        array(
          "type"      => 'textfield',
          "heading"   => __('Link Size', 'havnor-core'),
          "param_name" => "link_size",
          "value"      => "",
          "description" => __( "Enter the numeric value for link size in px.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
        ),
        array(
          "type"      => 'colorpicker',
          "heading"   => __('Link Hover Color', 'havnor-core'),
          "param_name" => "link_hover_color",
          "value"      => "",
          "description" => __( "Pick your link hover color.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-two',
          ),
        ),
        HavnorLib::vt_notice_field(__( "Button Styling", 'havnor-core' ),'tle_opt','cs-warning', 'Style'), // Notice
        array(
          "type" => "textfield",
          "heading" => __( "Button Text Size", 'havnor-core' ),
          "param_name" => "btn_text_size",
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Button Border Radius", 'havnor-core' ),
          "param_name" => "btn_border_radius",
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Text Color", 'havnor-core' ),
          "param_name" => "btn_text_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Text Hover Color", 'havnor-core' ),
          "param_name" => "btn_text_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Background Color", 'havnor-core' ),
          "param_name" => "btn_bg_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Background Hover Color", 'havnor-core' ),
          "param_name" => "btn_bg_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Border Color", 'havnor-core' ),
          "param_name" => "btn_border_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Button Border Hover Color", 'havnor-core' ),
          "param_name" => "btn_border_hover_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
        ),

        HavnorLib::vt_notice_field(__( "Spacings & Background", 'havnor-core' ),'rmr_opt','cs-warning', 'Style'), // Notice
        array(
          "type" => "textfield",
          "heading" => __( "Service Section Top Space", 'havnor-core' ),
          "param_name" => "service_top",
          'value' => '',
          "description" => __( "Enter service section top space.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Service Section Bottom Space", 'havnor-core' ),
          "param_name" => "service_btm",
          'value' => '',
          "description" => __( "Enter service section bottom space.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "colorpicker",
          "heading" => __( "Section Background Color", 'havnor-core' ),
          "param_name" => "service_bg_color",
          'value' => '',
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space', 
          'dependency' => array(
            'element' => 'service_style',
            'value' => 'service-five',
          ),
        ),
        HavnorLib::vt_notice_field(__( "Spacings Item Space", 'havnor-core' ),'rmr_opt','cs-warning', 'Style'), // Notice
        array(
          "type" => "textfield",
          "heading" => __( "Service Item Top Space", 'havnor-core' ),
          "param_name" => "service_item_top",
          'value' => '',
          "description" => __( "Enter service item top space.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Service Item Bottom Space", 'havnor-core' ),
          "param_name" => "service_item_btm",
          'value' => '',
          "description" => __( "Enter service item bottom space.", 'havnor-core'),
          "group" => __( "Style", 'havnor-core'),
          'edit_field_class'  => 'vc_col-md-6 vc_column vt_field_space',
        ),

      )
    ) );
  }
}
