<?php
/**
 * Portfolio - Shortcode Options
 */
add_action( 'init', 'havnor_portfolio_vc_map' );
if ( ! function_exists( 'havnor_portfolio_vc_map' ) ) {
  function havnor_portfolio_vc_map() {
    vc_map( array(
      "name" => __( "Portfolio", 'havnor-core'),
      "base" => "havnor_portfolio", 
      "description" => __( "Portfolio Styles", 'havnor-core'),
      "icon" => "fa fa-briefcase color-pink",
      "category" => HavnorLib::havnor_cat_name(),
      "params" => array(

        array(
          'type' => 'dropdown',
          'heading' => __( 'Portfolio Style', 'havnor-core' ),
          'value' => array(
            __( 'Style One (Grid)', 'havnor-core' )   => 'one',
            __( 'Style Two (Grid)', 'havnor-core' )   => 'two',
            __( 'Style Three (Masonry)', 'havnor-core' ) => 'three',
            __( 'Style Four (Slider)', 'havnor-core' )  => 'four',
            __( 'Style Five (Grid)', 'havnor-core' )  => 'five',
          ),
          'admin_label' => true,
          'param_name' => 'portfolio_style',
          'description' => __( 'Select your portfolio style.', 'havnor-core' ),
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Columns', 'havnor-core' ),
          'value' => array(
            __( 'Select Portfolio Columns', 'havnor-core' ) => '',
            __( 'Column Two', 'havnor-core' ) => '2',
            __( 'Column Three', 'havnor-core' ) => '3',
          ),
          'admin_label' => true,
          'param_name' => 'portfolio_column',
          'description' => __( 'Select your portfolio column.', 'havnor-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Limit', 'havnor-core'),
          "param_name"  => "portfolio_limit",
          "value"       => "",
          'admin_label' => true,
          "description" => __( "Enter the number of items to show.", 'havnor-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),

        array(
    			"type"        => "notice",
    			"heading"     => __( "Enable & Disable", 'havnor-core' ),
    			"param_name"  => 'ends_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Filter', 'havnor-core'),
          "param_name"  => "portfolio_filter",
          "value"       => "",
          "std"         => true,
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
        ),
        array(
          "type"        =>'checkbox',
          "heading"     =>__('Pagination', 'havnor-core'),
          "param_name"  => "portfolio_pagination",
          "value"       => "",
          "std"         => true,
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' => array('one','two','three','five'),
          ),
        ),
        array(
          'param_name'      => 'portfolio_pagination_type',
          'type'    => 'dropdown',
          'heading'   => esc_html__('Blog Pagination Type', 'havnor-core'),
          'value'        => array(
            __( 'Select Pagination Type', 'havnor-core' ) => '',
            __( 'Ajax Infinite Scroll', 'havnor-core' ) => 'infinite-scroll',
            __( 'Ajax Button', 'havnor-core' ) => 'load-more',
            __( 'Navigation', 'havnor-core' ) => 'navigation',
          ),
          'dependency' => array(
            'element' => 'portfolio_pagination',
            'value' => 'true',
          ),
        ),
        array(
          'param_name' => 'load_more_btn_txt',
          'type'       => 'textfield',
          'heading'      => esc_html__('Load More Button Text', 'fraxos'),
          'dependency' => array(
            'element' => 'portfolio_pagination_type',
            'value' => 'load-more',
          ),
        ),

        array(
    			"type"        => "notice",
    			"heading"     => __( "Listing", 'havnor-core' ),
    			"param_name"  => 'lsng_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order', 'havnor-core' ),
          'value' => array(
            __( 'Select Portfolio Order', 'havnor-core' ) => '',
            __('Asending', 'havnor-core') => 'ASC',
            __('Desending', 'havnor-core') => 'DESC',
          ),
          'param_name' => 'portfolio_order',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order By', 'havnor-core' ),
          'value' => array(
            __('None', 'havnor-core') => 'none',
            __('ID', 'havnor-core') => 'ID',
            __('Author', 'havnor-core') => 'author',
            __('Title', 'havnor-core') => 'title',
            __('Date', 'havnor-core') => 'date',
            __('Name', 'havnor-core') => 'name',
            __('Modified', 'havnor-core') => 'modified',
            __('Random', 'havnor-core') => 'rand',
            __('Menu Order', 'havnor-core') => 'menu_order',
          ),
          'param_name' => 'portfolio_orderby',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Show only certain categories?', 'havnor-core'),
          "param_name"  => "portfolio_show_category",
          "value"       => "",
          "description" => __( "Enter category SLUGS (comma separated) you want to display.", 'havnor-core')
        ),
        HavnorLib::vt_class_option(),

        // Stylings
        array(
    			"type"        => "notice",
    			"heading"     => __( "Filter", 'havnor-core' ),
    			"param_name"  => 'flst_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
          "group"       => __('Style', 'havnor-core'),
    		),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Color', 'havnor-core'),
          "param_name"  => "filter_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_filter',
            'value' => 'true',
          ),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Active Color', 'havnor-core'),
          "param_name"  => "filter_active_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_filter',
            'value' => 'true',
          ),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Line Color', 'havnor-core'),
          "param_name"  => "filter_line_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_filter',
            'value' => 'true',
          ),
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Text Size', 'havnor-core'),
          "param_name"  => "filter_size",
          "value"       => "",
          "group"       => __('Style', 'havnor-core'),
          "description" => __( "Enter filter text size in px.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_filter',
            'value' => 'true',
          ),
        ),

        // Size
        array(
    			"type"        => "notice",
    			"heading"     => __( "Item Style", 'havnor-core' ),
    			"param_name"  => 'itm_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
          "group"       => __('Style', 'havnor-core'),
    		),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Image Overlay Color', 'havnor-core'),
          "param_name"  => "image_overlay_color",
          "value"       => "rgba(0, 0, 0, 0.6)",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Portfolio Info Background Color', 'havnor-core'),
          "param_name"  => "info_bg_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Portfolio Info Background Hover Color', 'havnor-core'),
          "param_name"  => "info_bg_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Title Size', 'havnor-core'),
          "param_name"  => "portfolio_title_size",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Title Color', 'havnor-core'),
          "param_name"  => "portfolio_title_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Title Hover Color', 'havnor-core'),
          "param_name"  => "portfolio_title_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Categroy Color', 'havnor-core'),
          "param_name"  => "portfolio_cat_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Category Hover Color', 'havnor-core'),
          "param_name"  => "portfolio_cat_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Category Size', 'havnor-core'),
          "param_name"  => "portfolio_cat_size",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'havnor-core'),
        ),
        // Carousel
        array(
          "type"        => "notice",
          "heading"     => 'Basic Options',
          "param_name"  => 'bsic_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Loop?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_loop",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          "description" => __( "Continuously moving carousel, if enabled.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Items", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_items",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how many items you want in per slide.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Margin", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_margin",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Enter the numeric value of how much space you want between each carousel item.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Dots", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_dots",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "If you want Carousel Dots, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Auto Play & Interaction',
          "param_name"  => 'apyi_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Autoplay Timeout", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay_timeout",
          'value' => '',
          "description" => __( "Change carousel Autoplay timing value. Default : 5000. Means 5 seconds.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Autoplay", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoplay",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want to start Carousel automatically, enable it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Animate Out", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_animate_out",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "CSS3 animation out.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Mouse Drag?", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mousedrag",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "If you want Mouse Drag, check it.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Width & Height',
          "param_name"  => 'wah_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Width", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autowidth",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Width automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "checkbox",
          "heading" => __( "Auto Height", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_autoheight",
          "on_text" => __( "Yes", 'havnor-core' ),
          "off_text" => __( "No", 'havnor-core' ),
          "value" => '',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          "description" => __( "Adjust Auto Height automatically for each carousel items.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type"        => "notice",
          "heading"     => 'Responsive Options',
          "param_name"  => 'res_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => 'Carousel',
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Tablet", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_tablet",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in tablet.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),
        array(
          "type" => "textfield",
          "heading" => __( "Small Mobile", 'havnor-core' ),
          "group" => __( "Carousel", 'havnor-core' ),
          "param_name" => "carousel_small_mobile",
          'value' => '',
          'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
          "description" => __( "Enter number of items to show in small mobile.", 'havnor-core'),
          'dependency' => array(
            'element' => 'portfolio_style',
            'value' =>'four',
          ),
        ),

      )
    ) );
  }
}
